
ALTER TABLE public.agent_tasks
  ADD COLUMN IF NOT EXISTS schedule_type TEXT DEFAULT 'once',
  ADD COLUMN IF NOT EXISTS cron_expression TEXT,
  ADD COLUMN IF NOT EXISTS task_skills JSONB,
  ADD COLUMN IF NOT EXISTS task_mode TEXT,
  ADD COLUMN IF NOT EXISTS parallel_execution BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS parallel_subtasks JSONB,
  ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_run TIMESTAMPTZ;
