
ALTER TABLE public.ai_agents
  ADD COLUMN IF NOT EXISTS allowed_tools TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS system_prompt TEXT,
  ADD COLUMN IF NOT EXISTS max_tool_rounds INT NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS writing_style TEXT,
  ADD COLUMN IF NOT EXISTS response_length TEXT,
  ADD COLUMN IF NOT EXISTS language TEXT NOT NULL DEFAULT 'he';
