project_id = "jnzguisakdtcollxmgzd"

[functions.delete-user]
verify_jwt = true

[functions.invite-user]
verify_jwt = true

[functions.cleanup-empty-leads]
verify_jwt = false

[functions.webhook-lead-intake]
verify_jwt = false
