export {
  applyZoomLinkToEvent,
  buildMeetConferenceData,
  collectExtraAttendeeEmails,
  conferenceKindFromUrl,
  createZoomMeeting,
  eventDurationMinutes,
  extractConferenceUrl,
  fetchZoomAccessToken,
  googleCalendarGetEvent,
  googleCalendarPatchEvent,
  googleEventPatchUrl,
  mergeNamedPrimaryAttendee,
  resolveCarmenAttendeeEmail,
  resolveRequestedConference,
  summarizeEventResult,
  updateExistingCalendarEvent,
  zoomUnavailableMessage,
} from './calendar-conference.mjs';
